services:
  - type: web
    name: pdf-engine
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/start.js
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: NODE_ENV
        value: production
