services:
  - type: web
    name: pdf-engine
    runtime: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node src/start.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
